# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(selfW):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://ligamagic.com")
    WebDriverWait(self.driver, 10000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//input[@id=\'mainsearch\']")))
    self.driver.find_element(By.XPATH, "//input[@id=\'mainsearch\']").send_keys("teferi\'s protection")
    self.driver.find_element(By.XPATH, "//input[@id=\'mainsearch\']").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 10000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//div[@id=\'mobile-precos-menor\']")))
    self.driver.find_element(By.CSS_SELECTOR, "#line_e7798405 > .e-col9-mobile .fFtBb").click()
    self.driver.find_element(By.CSS_SELECTOR, "#line_e7798405 .e-mob-preco").click()
    self.driver.find_element(By.CSS_SELECTOR, "#line_e7842819 .e-mob-preco").click()
    self.driver.find_element(By.CSS_SELECTOR, "#line_e7810756 .e-mob-preco").click()
  


test = TestTest()

test.setup_method()
test.test_test()
# test.teardown_method()